pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)  // CHANGED THIS LINE
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Orbita Launcher"
include ':app'